# SPDX-FileCopyrightText: 2026 NOI Techpark <digital@noi.bz.it>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

services:
  pelias-opendatahub-importer:
    image: ${DOCKER_IMAGE_PELIAS_OPENDATAHUB_IMPORTER}:${DOCKER_TAG}
    build:
      context: ../
      dockerfile: infrastructure/docker/pelias-opendatahub-importer/Dockerfile
